### PR TITLE
renaming shared to default

### PR DESCRIPTION
**Pull request by RecherJ**
inspired by Apple NotificationCenter class.

### CODE REVIEW

**Comment by jianstm** [comment]
@RecherJ Well, I have some reservations about it.

In my opinion, `shared` and `default` have different meanings in their context. Using `default` means, this is the default one, but you can always use your own one, e.g. `FileManager.default`. But `shared` trends to say, this is a common one, all tasks are using this. 

I might expose `TaskCenter` in the future and allow developers to create their own center, just like `NotificationCenter`, but for now, let's just leave it here, what do you think?

**Comment by RecherJ** [comment]
all right, respect author's opinion. you understand deeply than me about this library.  :]

**Comment by jianstm** [comment]
@RecherJ No, it's a hub, not a controller, so i believe `TaskCenter` is fine here. Actually, I like `TaskHub` better, 🤣.

BTW, the second part(about `guard` statements) of this request looks good to me, would you mind opening a pr for that? Thank you for your warm contributions! 🙏

**Comment by RecherJ** [comment]
my pleasure 😁

**Comment by jianstm** [comment]
@RecherJ I don't understand. If you mean merge this request then revert `TaskCenter` part, I won't do that. I think that's an abuse of `revert`.

**Comment by jianstm** [comment]
@RecherJ Don't worry, then i'm going to close this pr. 😉

**Pull request closed without merging**
